# Generated by Django 5.0.6 on 2024-05-23 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_vehicledata_vehicle_owner_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicledata",
            name="vehicle_owner_contact",
            field=models.CharField(max_length=50),
        ),
    ]
